# .github/workflows/test.yml

name: Format

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev

      - name: Check for unformatted python code.
        run: pipenv run black --check -l 80 .

      - name: Format and push python files.
        if: failure()
        run: |
          pipenv run black -l 80 .
          git config --global user.name github-actions
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
          git commit -am "Automated black formatting"
          git push
